if (!require("BiocManager"))
  install.packages("BiocManager")
BiocManager::install("maftools")
library(maftools)
laml <- read.maf(maf = "analysis_10_wgs.combined_maf_v2_maftools.maf")
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
oncoplot(maf = laml, top = 30, removeNonMutated = TRUE)
write.mafSummary(maf = laml, basename = 'laml')
oncostrip(maf = laml, genes = c('TP53','RB1'), removeNonMutated = TRUE, showTumorSampleBarcodes = TRUE)
